import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="flex flex-row justify-center w-full">
        <ul className=" w-full flex flex-row justify-around">
          <li>
            <Link href="/shop">Shop</Link>
          </li>
          <li>
            <Link href="/about">About us</Link>
          </li>
          <li>
            <Link href="/other">Other</Link>
          </li>
          <li>
            <Link href="/cart">Shopping cart</Link>
          </li>
          <li>
            <Link href="/login">Register/Log in</Link>
          </li>
        </ul>
        </nav>{children}
      </body>

    </html>
  )
}